-- 3) Construa uma trigger para dar baixa do empréstimo (locação) do filme
-- — que o usuário alugar (supondo que exista um campo com a quantidade no cadastro do filme). -- Crie um campo 'quantidade' em film
